name: build

on:
  push:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: init env
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd
          sudo timedatectl set-timezone "$TZ"
          
      - name: checkout
        uses: actions/checkout@v4   
        
      - name: clone repo
        run: git clone -b openwrt-25.12 --single-branch --filter=blob:none https://github.com/immortalwrt/immortalwrt immortalwrt
        
      - name: cache
        uses: stupidloud/cachewrtbuild@main
        with:
          ccache: 'true'
          prefix: ${{ github.workspace }}/immortalwrt
          mixkey: x86-64

      - name: load file
        run: |
          cp .config immortalwrt
          cp config-6.12 immortalwrt/target/linux/x86
          cp feeds.conf.default immortalwrt

      - name: execute before script
        run: |
          chmod +x before-installing-feed.sh
          cd immortalwrt
          bash $GITHUB_WORKSPACE/before-installing-feed.sh

      - name: update & install feeds
        run: immortalwrt/scripts/feeds update -a && immortalwrt/scripts/feeds install -a
        
      - name: execute after script
        run: |
          chmod +x after-installing-feed.sh
          cd immortalwrt
          bash $GITHUB_WORKSPACE/after-installing-feed.sh
                  
      - name: build
        id: build
        run: |
          cd immortalwrt
          make defconfig
          make -j$(nproc)
          echo "status=success" >> $GITHUB_OUTPUT
          
      - name: ssh
        if: failure()
        uses: mxschmitt/action-tmate@v3

      - name: Organize files
        id: organize
        if: steps.build.outputs.status == 'success' && !cancelled()
        run: |
          cd immortalwrt/bin/targets/*/*
          rm -rf packages
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload firmware directory to artifact
        uses: actions/upload-artifact@main
        if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
          name: build
          path: ${{ env.FIRMWARE }}
