name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    
    steps:
      - name: init env
        run: |
          chmod -R 777 .
          export DEBIAN_FRONTEND=noninteractive
          apt update -y
          apt full-upgrade -y
          apt install -y sudo tzdata ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd
          ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          dpkg-reconfigure -f noninteractive tzdata

      - name: create user
        run: |
          useradd -m -s /bin/bash runner
          echo "runner ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
          
      - name: checkout
        uses: actions/checkout@v4
        
      - name: Fix directory permissions
        run: |
          sudo chown -R runner:runner /home/runner/work/immortalwrt/immortalwrt/immortalwrt
        
      - name: clone repo
        run: sudo -u runner git clone -b openwrt-25.12 --single-branch --filter=blob:none https://github.com/immortalwrt/immortalwrt immortalwrt

      - name: cache
        uses: stupidloud/cachewrtbuild@main
        with:
          ccache: 'true'
          prefix: ${{ github.workspace }}/immortalwrt
          mixkey: x86-64

      - name: load file
        run: |
          sudo -u runner cp .config immortalwrt
          sudo -u runner cp config-6.12 immortalwrt/target/linux/x86
          sudo -u runner cp feeds.conf.default immortalwrt

      - name: execute before script
        run: |
          sudo -u runner chmod +x before-installing-feed.sh
          sudo -u runner cd immortalwrt
          sudo -u runner bash $GITHUB_WORKSPACE/before-installing-feed.sh

      - name: update & install feeds
        run: sudo -u runner immortalwrt/scripts/feeds update -a && sudo -u runner immortalwrt/scripts/feeds install -a
        
      - name: execute after script
        run: |
          sudo -u runner chmod +x after-installing-feed.sh
          sudo -u runner cd immortalwrt
          sudo -u runner bash $GITHUB_WORKSPACE/after-installing-feed.sh
                  
      - name: build
        id: build
        run: |
          sudo -u runner cd immortalwrt
          sudo -u runner make defconfig
          sudo -u runner make -j$(nproc)
          sudo -u runner echo "status=success" >> $GITHUB_OUTPUT
          
      - name: ssh
        if: failure()
        uses: mxschmitt/action-tmate@v3

      - name: Organize files
        id: organize
        if: steps.build.outputs.status == 'success' && !cancelled()
        run: |
          sudo -u runner cd immortalwrt/bin/targets/*/*
          sudo -u runner rm -rf packages
          sudo -u runner echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          sudo -u runner echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload firmware directory to artifact
        uses: actions/upload-artifact@main
        if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
          name: build
          path: ${{ env.FIRMWARE }}
